name: Hockey Addiction
favicon: null
layout_spectrum: 0.76971
typography_spectrum: 0.94879
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#777777'
    - '#9b9b9b'
    - '#ed1c24'
    - '#efefef'
  brandStrength: 0.19166356604546309
  lightness: 0.6112183954101056
  saturation: 0.09789420384913683
  rhythmicContrast: 0
purpose: []
